title: My personal blog - Yort
email: yort.feng@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/post" # the subpath of your site, e.g. /blog
url: "https://yorthub.com" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: Yort # add your name
author-pic: yort-face.jpg
about-author: My name is Yort. I'm a half-stack programmer and have been doing it as a job for nearly 7 years, I wrote java codes in the first 5 years of my career, after that I more some script languages, like Nodejs, typescript, react, etc...
Anyway, I’m trying to write some notes of learning English and Programing, hope you like it.

# Contact links
email: yort.feng@gmail.com # Add your Email address
phone: 18974838697
# website: # Add your website, do not add http://
# linkedin: # Add your Linkedin handle
stackoverflow: https://stackoverflow.com/users/3762105/troy
github: yort-feng # Add your Github handle
instagram: yort.feng
twitter: '@yort_feng' # Add your Twitter handle
# facebook: # Add your Facebook handle
# pinterest: # Add your Pinterest handle

# Newsletter
# mailchimp: # Add your MailChimp form identifier.

# Disqus
# discus_identifier: mr-brown # Add your discus identifier

# Tracker
# analytics: # Google Analytics

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]
